#-------------------------------------------------
# cubanker project Makefile
#-------------------------------------------------
# Do nothing for now..but in future we will
# 1. run COntrol Panel to
#  a. configure DB 
#  b. set rights etc
